### ISSUE TITLE
First version

### ISSUE THREAD

**Issue by sebasguts** [gap-system/gap-docker-base#1]
I created the Dockerfile for this repository in

https://github.com/sebasguts/gap-docker-base

should I upload it here and make my repo a fork of it?

**Comment by olexandr-konovalov** [comment]
Thanks - looks good. Since here `gap-docker-base` is still empty, perhaps I can delete it and you can transfer yours to GAP organisation (https://help.github.com/articles/transferring-a-repository/) and then fork it?

**Comment by sebasguts** [comment]
I will take care of it. Unfortunately, you cannot fork an empty repository.

**Comment by olexandr-konovalov** [comment]
Good to know. Of course, I could populate it with README.md if I knew :)
