### ISSUE TITLE
Install SageMath in the image

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap-docker-base#24]
I would like to add the Ubuntu package [sagemath](https://packages.ubuntu.com/bionic/sagemath) to the image, since this CAS can be used as a backend by `RingsForHomalg`. Would this be accepted?

**Comment by ChrisJefferson** [comment]
How much bigger does that make the image?

**Comment by zickgraf** [comment]
When not installing recommended packages, "1229 MB of additional disk space will be used", because many  dependencies (like an additional copy of GAP itself) are pulled in. This would about double the size of the `gap-docker` image which I guess is too much.  I tried to compile a minimal version myself but I think this is not worth the effort. So all in all I'm closing this request.

**Comment by olexandr-konovalov** [comment]
Yes, too much, I am afraid. OTOH, is there a docker container for SageMath which you can use?

**Comment by zickgraf** [comment]
Yes, there is, but my primary applications are CI tests which is why I also want an image including gap-master, which SageMath does not provide :-(
