### ISSUE TITLE
Automated build does not work

### ISSUE THREAD

**Issue by sebasguts** [gap-system/gap-docker-base#3]
The automated build does not work for this image. I cannot see any error messages, but I think we might simply run out of time or memory. This are the restrictions:

https://forums.docker.com/t/automated-build-resource-restrictions/1413

Should we split up the image or build it ourselfes? I would vote for building it ourselfes.

**Comment by olexandr-konovalov** [comment]
Thanks, I'm investigating. First of all, I can't build it locally:

```
INFO[2080] The command [/bin/sh -c cd /tmp     && wget http://www.polymake.org/lib/exe/fetch.php/download/polymake-2.14.tar.bz2     && tar -xf polymake-2.14.tar.bz2     && cd polymake-2.14 \    && ./configure --without-java --with-gmp=system     && make -j     && sudo make install     && cd /tmp     && rm -rf polymake*] returned a non-zero code: 137 
```

**Comment by sebasguts** [comment]
Do you have some detailed error output? I actually can build it locally, and I thought it would be the same on all systems.

**Comment by olexandr-konovalov** [comment]
The last line before the `INFO` message above was

```
/usr/bin/perl /tmp/polymake-2.14/support/guarded_compiler.pl g++ -c -o perl/auto-far_points.o -fPIC -I/tmp/polymake-2.14/include/core-wrappers -I/tmp/polymake-2.14/include/core -I/tmp/polymake-2.14/include/app-wrappers -I/tmp/polymake-2.14/include/apps -march=native -ftemplate-depth-200 -Wall -Wno-strict-aliasing -Wno-parentheses -fwrapv -fopenmp -Isystem/include -DPOLYMAKE_APPNAME=polytope -DNDEBUG -DPOLYMAKE_DEBUG=0 -O3 -MD     /tmp/polymake-2.14/apps/polytope/src/perl/auto-far_points.cc
```

Not too informative, as it does not display any error messages... Will try later...

**Comment by sebasguts** [comment]
Interesting anyway. I thought the build process would be done in a container, so everything should be the same. You are using Boot2Docker on a Mac, I guess?

**Comment by olexandr-konovalov** [comment]
Yes, on Mac. I could try Ubuntu 14 and also try to log in into the docker image on Mac and try to repeat all commands step by step but not until Friday. If you would like to investigate this in the meantime, please go ahead.

**Comment by sebasguts** [comment]
Did some investigations, but I cannot see any bad. On my ArchLinux with Docker version 1.5.0, build a8a31ef it works fine, maybe this is too old.

**Comment by snim2** [comment]
It might be worth just retstarting the automated build on Docker hub, in case it was just some random error. If you can't reproduce the failure locally you might as well have a go....

**Comment by sebasguts** [comment]
I think the time and space limitations will still make the build a failure. But it is worth a try.

**Comment by olexandr-konovalov** [comment]
Ok, so we have that with the Docker file from gap-container automated build works fine. Maybe we could try to add `RUN` blocks to Dockerfile one by one and see how the automated build goes?

**Comment by sebasguts** [comment]
Trying this right now.

**Comment by sebasguts** [comment]
Seems like 4ti2 causes the problem. It is strange, since I can build the exact same commit on my maschine. I try to build everything except 4ti2.

**Comment by olexandr-konovalov** [comment]
Let's try to build 4ti2 only and then polymake only. I suspect that indeed there may be limitations of Docker hub. If this will be proved to be the case, then either we have to split the image or build ourselves. I am not really happy with doing that (i.e. building it manually), but if this has to be done only once after each minor release, it would be tolerable.

**Comment by olexandr-konovalov** [comment]
P.S. I've tried to build container with 4ti2 locally and it does not seem to work properly:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src/4ti2 -D_4ti2_GMP_ -I./.. -D__STDC_LIMIT_MACROS -DNDEBUG -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -Wall -std=c++0x -MT lib4ti2gmp_la-SyzygyGeneration.lo -MD -MP -MF .deps/lib4ti2gmp_la-SyzygyGeneration.Tpo -c SyzygyGeneration.cpp -o lib4ti2gmp_la-SyzygyGeneration.o
mv -f .deps/4ti2int64-circuits_main.Tpo .deps/4ti2int64-circuits_main.Po
mv -f .deps/4ti2int32-circuits_main.Tpo .deps/4ti2int32-circuits_main.Po
mv -f .deps/4ti2gmp-circuits_main.Tpo .deps/4ti2gmp-circuits_main.Po
mv -f .deps/4ti2int32-rays_main.Tpo .deps/4ti2int32-rays_main.Po
mv -f .deps/4ti2gmp-rays_main.Tpo .deps/4ti2gmp-rays_main.Po
mv -f .deps/4ti2int64-rays_main.Tpo .deps/4ti2int64-rays_main.Po
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
...
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
g++: internal compiler error: Killed (program cc1plus)
g++: internal compiler error: Killed (program cc1plus)
virtual memory exhausted: Cannot allocate memory
Please submit a full bug report,
with preprocessed source if appropriate.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
../../libtool: line 1763:  7803 Segmentation fault      g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src/4ti2 -D_4ti2_INT32_ -I./.. -D__STDC_LIMIT_MACROS -DNDEBUG -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -Wall -std=c++0x -MT lib4ti2int32_la-BinomialFactory.lo -MD -MP -MF .deps/lib4ti2int32_la-BinomialFactory.Tpo -c BinomialFactory.cpp -o lib4ti2int32_la-BinomialFactory.o
Makefile:2341: recipe for target 'lib4ti2int64_la-BasicGeneration.lo' failed
make[3]: *** [lib4ti2int64_la-BasicGeneration.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
make[3]: *** Waiting for unfinished jobs....
```

**Comment by sebasguts** [comment]
So it seems that you run out of memory, and since dockerhub restricts the memory for the automated build, this could be the cause of the failure for both polymake and 4ti2. Since my docker runs on a Linux machine, I do not depend on some virtual machine and have 128 GB of Ram to test it. Maybe I should remove the -j flag for the compilation to save some memory, but then it might take too much time. I will try it anyway.

I would highly suggest to build it locally. I can actually do this on our server once a week/day/whenever it seems appropriate. I could then push it to my account and we can make gap-docker depend on that container?

**Comment by olexandr-konovalov** [comment]
Ok, please try without `-j` first. 

We may of course make the `gap-docker-base` first in a chain, and then build `gap-docker-container` and then `gap-docker` but this could be an overhead - those who are interested in `gap-docker-container` may appreciate having a smaller image without all other packages. So indeed, placing `gap-docker-base` in between those two sounds good. I don't expect we will need to rebuild it often - it will be needed only after a GAP release. 

So, if removing `-j` does not help, please go ahead with building it locally and pushing it, and making `gap-docker` depending on it.

**Comment by sebasguts** [comment]
-j seems to give us a time out, the last build failed, too. I will push the image myself. We should agree on an update scheme, maybe once a week, or whenever gap-container changes?
