### ISSUE TITLE
LinBox missing

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker-base#5]
linboxing package provides an interface to LinBox (http://www.linalg.org/). The package may be tricky to compile, so one should first pull `gap-docker` container, install there LinBox and try to compile linboxing, and only If successful, add LinBox to `gap-docker-base`.

**Comment by sebasguts** [comment]
This seems to be a larger problem. I tried to install it with it's dependencies, and they (givaro and fflas-ffpack) work fine, but linbox tells me it is unable to find GMP. I wrote the authors, but now this might take some time.

**Comment by olexandr-konovalov** [comment]
Thanks for trying! I think we should agree of not adding it for the moment. FYI, it was also not supported in the [rsync-based GAP distribution](http://www.math.rwth-aachen.de/~Frank.Luebeck/gap/rsync/). The first step would be to see what changes need to be done to linboxing to use a current version of LinBox, which can be installed with only small problems.

**Comment by olexandr-konovalov** [comment]
The linboxing package now has a repository: https://github.com/gap-packages/linboxing - if there will be any identified changes necessary to get it to work, please submit PRs there.

**Comment by olexandr-konovalov** [comment]
The linboxing package will not be included in GAP 4.10 distribution.
