### ISSUE TITLE
Switch to fplll 5

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker-base#8]
As @laurentbartholdi says, we need to switch to fplll 5, which is not compatible with fplll 4 (see https://github.com/gap-packages/float/issues/31#issuecomment-348704888).

**Comment by olexandr-konovalov** [comment]
Is there a commit for this missing?

**Comment by sebasguts** [comment]
Yeah, forgot to push it here, sorry. Will do now.
