### ISSUE TITLE
Update Pari/GP (and possibly other packages)

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker-base#9]
The current version in the Dockerfile is 2.7.3.  We need to switch to 2.9.4 (see https://pari.math.u-bordeaux.fr/download.html) to make Alnuth package working.

**Comment by olexandr-konovalov** [comment]
In addition, let's look at other packages/libraries. So here is the full list:
- [x] Pari/GP 2.7.3 -> 2.9.5 in 26db608566dad9b105ae91a261ed9757a0613421
- [x] CXSC (for Float): 2.5.4 latest
- [x] libfplll (for Float): 5.2.1 latest in 26db608566dad9b105ae91a261ed9757a0613421
- [ ] flint (for Singular): https://github.com/wbhart/flint2.git - is there a way to get particular revision known to work instead of using the tip of the master branch?
- [x] Singular: 4.1.0 -> 4.1.1 in 26db608566dad9b105ae91a261ed9757a0613421
- [x] Polymake: now done via `apt-get`
- [x] 4ti2: 1.6.3 -> 1.6.7 in 26db608566dad9b105ae91a261ed9757a0613421

**Comment by olexandr-konovalov** [comment]
@sebasguts seems fine now, except my question about flint - I am not comfortable with getting the latest development version all the time.

**Comment by sebasguts** [comment]
At the moment, we could just pin it to the head commit that is currently there. Although I would not think of this version as better or worse than any other version, actually.

There is no recent release of flint, and the latest release is horribly outdated and might not even compile. I would actually leave it to be the latest version at the moment, and then fix a version if there is the next release.

**Comment by olexandr-konovalov** [comment]
@sebasguts ok - closing this, moving flint to #11
